project_id = "tgkksvazruzbghssnxde"

[functions.lender-summary]
verify_jwt = false

[functions.execute-workflow]
verify_jwt = true

[functions.send-invite]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = false

[functions.send-weekly-summary]
verify_jwt = false
